Unidata/netcdf-fortran

- docs/netcdf_fortran.3
These issues were reported by the lintian QA tools during the Debian package
build process.
> Fix hyphen used as minus sign issues in man page.

- .travis.yml
- CMakeLists.txt
Preparing a new maintenance release.
> Updates to netCDF fortran in support of the upcoming release.

- .travis.yml
- CMakeExtras/Makefile.am
- CMakeExtras/MatchNetCDFFortranTypes.cmake
- CMakeLists.txt
- RELEASE_NOTES.md
Some small changes in preparation for the next release.
> Github #67 plus a couple other small changes

- .travis.yml
- RELEASE_NOTES.md
Upgraded testing to work with changes in the C library.
> Updated to travis testing for netcdf-fortran.

- CMakeLists.txt
> Fix compiler issue on OSX

- fortran/Makefile.am
Fixing a few more dependencies. This PR comes after (or instead of) #178 .
I needed to fix these to get make -j distcheck working reliably.
> fixing some dependencies

- docs/netcdf_fortran.3
- fortran/Makefile.am
Fixes #26 
Fixing nf_set_log_level() in fortran api.
> added logging source to autotools build

- CMakeLists.txt
- RELEASE_NOTES.md
- nf03_test4/CMakeLists.txt
- nf03_test4/Makefile.am
> Fixes distribution of cmake-based large file tests

- configure.ac
> correctly detect absence of szip write capability

- fortran/nf_v2compat.c
Fixes #225 
This PR includes a warning fix. The status variable needs to be initialized to zero.
> Fix a warning in v2 code

- RELEASE_NOTES.md
- docs/netcdf-f77.md
- docs/netcdf-f90-sec6-variables.md
- fortran/netcdf4.inc
- fortran/netcdf_constants.f90
- nf_test4/CMakeLists.txt
- nf_test4/Makefile.am
- nf_test4/ftst_var_compact.F
> Adds support and test for compact storage

- nf03_test4/f90tst_io.f90
> fixed warning in f90tst_io.f90

- docs/netcdf-f90-sec6-variables.md
* Fixes 229
Minor documentation tweak.
> Removed reference to NF90_TYPE in documentation

- fortran/Makefile.am
- nf_test/Makefile.am
Fixes #244 
Fixes #242 
As suggested by @skosukhin in #238.
> Autotools build improvements

- Makefile.am
> Fix missing file

- CMakeLists.txt
* Fixes #321 
Cleanup of variables managed in CMakeLists.txt
> Fix error in cmake-generated nf-config

- .github/workflows/run_tests.yml
- fortran/expand-interfaces.py
- fortran/netcdf.f90
- fortran/netcdf_eightbyte_subset.f90
- fortran/netcdf_expanded_subset.f90
- fortran/netcdf_get_nd_expanded.f90
Wires in new Github Actions-based testing into #294 to get that merged.  Then we will move to releasing netCDF-C 4.9.0, so that we can prepare netCDF-Fortran 4.6.0.
> Wire in new tests in to PR #294

- nf_test/tst_f77_v2.F
Refactor of #330 to include the corrected Github Actions file, so that the PR by @edwardhartnett can pass CI and be merged.
> adding v2 api test

- .github/workflows/run_tests_linux.yml
Making a modest start at updating the github actions for netcdf-fortran.
> Updating github actions.

- .github/workflows/build.yml
- .gitignore
- docs/netcdf-f90-sec6-variables.md
- fortran/module_netcdf4_nc_interfaces.f90
- fortran/module_netcdf4_nf_interfaces.F90
- fortran/module_netcdf_nc_data.F90
- fortran/module_netcdf_nc_interfaces.f90
- fortran/module_netcdf_nf_data.F90
- fortran/netcdf4.inc
- fortran/netcdf4_externals.f90
- fortran/netcdf4_func.f90
- fortran/netcdf4_variables.f90
- fortran/netcdf4_visibility.f90
- fortran/netcdf_constants.f90
- fortran/nf_nc4.f90
- nf03_test4/CMakeLists.txt
- nf03_test4/Makefile.am
- nf03_test4/f90tst_vars5.f90
- nf03_test4/run_f90_par_test.sh
- nf_test4/CMakeLists.txt
- nf_test4/Makefile.am
- nf_test4/ftst_vars7.F
**Merge in after netCDF-C 4.9.0 release, in preparation for netCDF-Fortran 4.6.0** Reverts Unidata/netcdf-fortran#317
> "Add quantize feature to F77 and F90 APIs, with tests and documentation"

- nf03_test4/f90tst_parallel_compressed.F90
Otherwise, got an error message:
Note: The following floating-point exceptions are signalling: IEEE_DENORMAL
STOP 181
> initialize value_grid_yt_loc to zeros

- fortran/nf_dim.F90
dimid will be reset in the following code.
There are lots of same cases in "inq" functions.
> delete unuseful code
