- fortran/nf_logging.F90
Certain compilers (intel), does not allow putting a separator without having any identifiers.
> Removed identifier separator in nf_logging.F90

- configure.ac
- nf03_test/CMakeLists.txt
- nf03_test/Makefile.am
I believe the only reason the tst03_f77_v2 test failed to build with PGI was that it was being picky about needed to link to the module_tests object file.  Adding that to the build allows it to compile with PGI for me.
> Add module_tests.F90 to tst03_f77_v2 sources; Drop using_pgi test

- examples/F90/Makefile.am
parralel tests are not run directly, but via a script.
I'm running into a situation on the Fedora builders where mpich programs must be started via mpiexec, but currently the example/F90 parallel tests (and maybe others) are being run directly.  This PR is a start on fixing that.  However, I get the following error from run_f90_par_examples.sh (which wasn't being run before this change):
~~~~~
FAIL: run_f90_par_examples.sh
=============================
*** SUCCESS writing example file simple_xy_par.nc! 
*** SUCCESS reading example file simple_xy_par.nc! 
NetCDF: Attempt to extend dataset during NC_INDEPENDENT I/O operation. Use nc_va
NetCDF: Attempt to extend dataset during NC_INDEPENDENT I/O operation. Use nc_va
NetCDF: Attempt to extend dataset during NC_INDEPENDENT I/O operation. Use …
> Structure test configuration more like netcdf-c so that the

- fortran/nf_logging.F90
If USE_LOGGING=ON this is not propagated to a -DLOGGING compile line definition, which always results in an empty nf_logging.F90 file. (The NAG compiler refuses to accept an empty file.)  This commit addresses this by simply removing the #ifdef from nf_logging.F90; it seems to be unnecessary because both the cmake and autoconf configurations seem to be very careful about only including this source file when USE_LOGGING is ON.
> USE_LOGGING not propagated to LOGGING preprocessor macro

- acinclude.m4
Fedora rawhide no builds everything with -Werror=implicit-function-declaration which causes this check to fail due to implicit declaration of exit().
> Avoid compilation failure with -Werror=implicit-function-declaration

- examples/F90/simple_xy_par_wr2.f90
Previously, the `nf90_put_var` writes were done independently, but this
is not possible in the current NetCDF4 library, since unlimited
dimensions require collective writes.  As a result, this test was
failing on our system.
We have resolved the problem by switing from `nf90_independent` to
`nf90_collective` writes, and removing the rank 0 write test, which was
blocking the (now collective) `nf90_put_var` call.
> F90 parallel wr2 test: collective writes

- CMakeExtras/Makefile.am
- CMakeExtras/MatchNetCDFFortranTypes.cmake
- CMakeLists.txt
When I was integrating netcdf-fortran into Amber-MD's build system, I noticed that the `ENABLE_FORTRAN_TYPE_CHECKS` block in CMakeLists.txt (which seems important for portability) was marked as TODO.  Since my CMake-ized PNetcdf also needed this feature, I wrote it for you guys.  I have tested it on several machines and it seems to work fine.
I also made two other small changes to CMakeLists.txt: I removed the unnecessary full include paths to standard library modules, and I removed QUIET from the `find_package(netCDF)` call.  This makes it so the user gets a lot more information if it can't find netcdf.
Let me know if you have any questions or concerns.
> CMakeLists.txt: check for the C types that match Fortran ones.

- nf03_test/nf03_error.F
- nf03_test/nf03_test.F
- nf_test/nf_error.F
- nf_test/nf_test.F
Currently nf_test.F fails to return an error status for "make check" to catch.
In errore(), increasing nfails is redundent, as it calls errorc().
> consistent error out for nf_test.F and nf03_test.F

- nf03_test/f03tst_open_mem.F
The changes being made to the netcdf-c library
(see https://github.com/Unidata/netcdf-c/issues/1154)
caused the diskless testing in fortran to fail.
This should fix that.
> Fix use of diskless in Fortran test.

- configure.ac
- fortran/Makefile.am
- libsrc/Makefile.am
- libsrc/nfconfig.in
Fixes #101..
Fixes#103.
Fixes for configure.ac to get static builds working.
Also now correctly cleaning netcdf.inc with make clean.
> fixed configure.ac for static builds

- CMakeLists.txt
- configure.ac
- docs/netcdf-f77.md
- docs/netcdf-f90-sec6-variables.md
- fortran/module_netcdf4_nc_interfaces.f90
- fortran/module_netcdf4_nf_interfaces.F90
- fortran/netcdf4.inc
- fortran/netcdf4_externals.f90
- fortran/netcdf4_func.f90
- fortran/netcdf4_visibility.f90
- fortran/nf_lib.c
- fortran/nf_nc4.f90
- nf03_test/CMakeLists.txt
- nf03_test/Makefile.am
- nf_test/CMakeLists.txt
- nf_test/Makefile.am
- nf_test/ftst_filter.F
- nf_test/ftst_rengrps.F
re: Issue https://github.com/Unidata/netcdf-fortran/issues/104
Added nf_def_var_filter and nf_inq_var_filter to the fortran API.
Also added a testcase: f03tst_filter.F.
Not clear if this will work with F77.
May need some tweeking depending on the compiler used; I was
using gfortran version 7.
> Add filter support to the netcdf-fortram API

- configure.ac
- nf_test/Makefile.am
Fixes #123.
We have been getting some reports of netcdf-fortran build problems with static libraries.
Everyone is using static because pnetcdf now build static-only by default, so anyone including pnetcdf runs into the problem that they cannot build shared libraries if pnetcdf is static-only. The best answer is to rebuild pnetcdf with --enable-shared, but instead, people build netcdf-c and netcdf-fortran with --disable-shared.
Static only builds work fine in netcdf-fortran, but when not all necessary library locations are specified in LDFLAGS, the build fails in a confusing way. Instead of detecting the problem during the configure step, it is ignored by configure and the user sees the problem as a linking error.
The answer is to fail out in configure if the netcdf-c library cannot be …
> Detect inability to link to netcdf-c library at configure time

- nf-config.in
If user specific installation paths are specified for executables, libraries and include files, they are ignored and reset based on `$prefix`.
> bugfix in nf-config.in

- configure.ac
- examples/F90/simple_xy_par_rd.f90
- fortran/netcdf4_eightbyte.f90
- fortran/netcdf4_file.f90
- fortran/netcdf4_func.f90
- fortran/netcdf_expanded.f90
- fortran/netcdf_text_variables.f90
- fortran/nf_control.F90
- fortran/nf_dim.f90
- fortran/nf_genatt.f90
- fortran/nf_misc.f90
- fortran/nf_nc4.f90
- fortran/nf_var1io.F90
- nf_test/f90tst_parallel.F90
- nf_test/f90tst_rengrps.f90
- nf_test/f90tst_vars2.f90
- nf_test/f90tst_vars4.f90
- nf_test/tst_f90_nc4.f90
- nf_test/tst_io.f90
Fixes #146 
Part of #147.
In this PR I fix the problem of cache preemption being converted from float to int without multiplying by 100, resulting in a cache preemption of 0.
Also fixed many of the warnings in #147. Still some more to do.
This PR is ready to merge.
> fix cache preemption issue, also some warnings

- nf_test/Makefile.am
- nf_test/f90tst_nc4_par.F90
- nf_test/f90tst_parallel3.F90
- nf_test/f90tst_parallel_fill.f90
- nf_test/run_f90_par_test.sh
Fixes #162.
Fixes #134.
In this PR I finish a test program I started in 2009 and left incomplete - nf_test/f90tst_parallel_fill.f90, which tests fill values in parallel I/O reads and writes.
Also fixed failures relating to removal of nf_mpiio flag. We still need to use this flag in our tests, if we want to work with older versions of netcdf-c. I am testing from netcdf-c-4.6.0 onwards.
> Fix for remaining parallel I/O tests

- fortran/Makefile.am
- fortran/netcdf.f90
- fortran/netcdf4.f90
- fortran/typeSizes.f90
Fixes #177. 
In this PR I fix mod file dependency tacking.
I did this for the tests.mod file when re-doing the test directories. In this PR I do it for all the mod files in the fortran directory.
To reduce future confusion, I have renamed the (internal-only) mod file typeSizes to typesizes, matching the case of all the other mod files, and the case that gfortran and other fortran compilers want us to use for module names. This change will have no effect on user code.
With this PR, the .NOTPARALLEL directive is removed, and parallel (make -j) builds now work in all directories, demonstrating that all dependencies are being properly tracked.
> fix dependency tracking in fortran directory, enabling parallel (make -j) builds

- nf_test4/CMakeLists.txt
- nf_test4/Makefile.am
- nf_test4/ftst_filter.F
- nf_test4/run_tst_filter.sh
re: https://github.com/Unidata/netcdf-fortran/issues/169
This required a change both to netcdf-c and to netcdf-fortran.
For netcdf-c, see PR https://github.com/Unidata/netcdf-c/pull/1387
The fortran fix required creating a shell script: nf_test4/run_tst_filter.sh.
This script ensures that HDF5_PLUGIN_DIR is set to nf-config --prefix.
This assumes that you are using the version of netcdf-c where the bzip2
plugin is installed in the --prefix/lib dir as part of the netcdf-c
library install. This may not work correctly for Windows or OSX.
> Get filter test to work with Fortran

- fortran/nf_lib.c
- fortran/nf_v2compat.c
> fix compile error: NC_CLASSIC_MODEL

- fortran/Makefile.am
Fix error below when running autoreconf.
fortran/Makefile.am:127: warning: module_netcdf4_nc_interfaces.$(OBJEXT) was already defined in condition TRUE, which includes condition USE_NETCDF4 ...
fortran/Makefile.am:81: ... 'module_netcdf4_nc_interfaces.$(OBJEXT)' previously defined here
> duplicated module_netcdf4_nc_interfaces.$(OBJEXT)

- nf_test4/f03tst_open_mem.F
- nf_test4/ftst_groups.F
- nf_test4/ftst_types.F
- nf_test4/ftst_types2.F
- nf_test4/ftst_types3.F
- nf_test4/ftst_vars.F
- nf_test4/ftst_vars2.F
- nf_test4/ftst_vars3.F
- nf_test4/ftst_vars4.F
- nf_test4/ftst_vars5.F
- nf_test4/ftst_vars6.F
When using gfortran 4.4.7, I got compile error message below.
```
Making check in nf_test4
Fortran/netcdf-fortran/nf_test4/ftst_groups.F:44.72:
if (retval .ne. nf_noerr) stop retval                          
1
Error: Syntax error in STOP statement at (1)
```
Fortran stop statement: STOP [str] where str is a
string of no more that 5 digits or a character constant.
> Use of "stop retval" is not portable

- configure.ac
add NF_INT8_IS_C_LONG_LONG default setting when --disable-fortran-type-check is used to configure
> 64-bit integer: missing the case for --disable-fortran-type-check

- CMakeLists.txt
- configure.ac
When parallel I/O feature in NetCDF C library is detected enabled,
check if the supplied Fortran compiler supports MPI-IO. If not,
abort the configure command.
> Check FC supports MPI-IO at configure time

- nf03_test4/f90tst_parallel_fill.f90
> Fixes an issue with Intel Compiler 19

- docs/netcdf-f90-sec2-datasets.md
Tiny thing, but I saw it as I was reading the docs.
> Spelling fix in docs for cache_preemption

- CMakeLists.txt
- RELEASE_NOTES.md
- configure.ac
> Correct failure to compile on some mpi systems.

- configure.ac
- fortran/module_netcdf4_nf_interfaces.F90
- fortran/module_netcdf_nc_interfaces.f90
- fortran/netcdf4.inc
- fortran/netcdf4_externals.f90
- fortran/netcdf4_func.f90
- fortran/netcdf4_visibility.f90
- fortran/nf_nc4.f90
- nf03_test4/Makefile.am
- nf03_test4/f90tst_var_szip.f90
- nf_test4/Makefile.am
- nf_test4/ftst_var_szip.F
In this PR I add support for nc_def_var_szip to the F77 and F90 APIs, including tests.
Since this is adding a new function, only the current C master will work to build this. So this will fail travis. I suppose, @WardF , that you will want to release the C version, then update the Fortran tavis testing, then this PR will pass tests.
Fixes #215 
Fixes #213
> support nc_def_var_szip in Fortran APIs

- examples/F77/pres_temp_4D_rd.f
- examples/F77/pres_temp_4D_wr.f
- examples/F77/sfc_pres_temp_rd.f
- examples/F77/sfc_pres_temp_wr.f
- examples/F77/simple_xy_nc4_rd.f
- examples/F77/simple_xy_nc4_wr.f
- examples/F77/simple_xy_rd.f
- examples/F77/simple_xy_wr.f
- examples/F90/nc4_pres_temp_4D_wr.f90
- examples/F90/pres_temp_4D_rd.f90
- examples/F90/pres_temp_4D_wr.f90
- examples/F90/sfc_pres_temp_rd.f90
- examples/F90/sfc_pres_temp_wr.f90
- examples/F90/simple_xy_nc4_rd.f90
- examples/F90/simple_xy_nc4_wr.f90
- examples/F90/simple_xy_par_rd.f90
- examples/F90/simple_xy_par_wr.f90
- examples/F90/simple_xy_par_wr2.f90
- examples/F90/simple_xy_rd.f90
- examples/F90/simple_xy_wr.f90
Fixes #233 
Fixes #232 
This PR contains some updated locations for the documentation, plus clears up compile warnings in the examples.
> Fix warnings and documentation in examples

- fortran/Makefile.am
Getting the build dependencies right is about more than just enabling parallel builds.
Only if all the build dependencies are correct can we could on make building the correct files when we make a change. Since netcdf-fortran is somewhat complex, there are a lot of dependencies!
Part of #208
> Add missing build dependencies for Fortran

- fortran/Makefile.am
- nf_test/Makefile.am
In contrast to #221, this PR fixes parallel builds only:
1. `$(NETCDF3_CODES)` should be listed in `EXTRA_DIST`.
2. Some rules that have been copied from #221 mention unset variables, e.g. `$(netcdf_nc_interfaces_mod)`.
3. Added dependencies on `tests.mod` in `nf_test`.
4. If an object file is part of a libtool library, the dependencies on Fortran module files should mention `.lo` files and not `.$(OBJEXT)` files because `.$(OBJEXT)` files are not part of the dependency graph of the library according to `make`. This is, however, not the case for objects that get linked into an executable directly, which is why new dependencies in `nf_test` mention `.$(OBJEXT)` files.
I would also suggest the following improvements to the Makefiles:
1. Fortran module files should not be listed in …
> Fix parallel builds

- nf03_test4/f90tst_vars2.f90
- nf_test4/ftst_vars.F
Fixes #154 
Turns out this issue was caused by documentation problems. I added some tests while checking this issue out, they test get/set var cache from F77 and F90 APIs, with and without using nc_get/set_var_cache_ints().
> Tests to confirm get/set var cache working in F77 and F90 APIs

- nf03_test4/f90tst_vars2.f90
Fixes #253 
This comments out some test code which tests cache values. THese values are not set in paralell builds, so the test fails for parallel builds.
Since we don't do preprocessing, there's no easy way to ifdef..
> commented out cache value test because it doesnt work on parallel

- RELEASE_NOTES.md
- configure.ac
Fixes #251 
The answer is that the user must set LIBS to `nc-config --libs` for static building. I have changed the error message to remind them to do so.
Also I changed the way nc_def_var_szip was found, so that it is checked for after all the compiler stuff has been checked.
Thanks to @GeorgeVandenberghe-NOAA for helping track this down.
> Change error message to mention LIBS and static builds

- CMakeLists.txt
Currently, when using CMake, netcdf-fortran may build and fail to link if using netcdf-c < 4.7.4.
The autoconf build already has this check.
> CMake: Fail if nc_def_var_szip missing

- RELEASE_NOTES.md
- fortran/netcdf_file.f90
- fortran/netcdf_visibility.f90
- nf03_test/tst_f90.f90
- nf03_test4/f90tst_nc4.f90
While doing some work on the GFDL FMS package, which uses the netCDF F90 API, I realized that the nf90_inq_foramt() function is missing, though the nf_inq_format() function is present in the F77 API, and all the appropriate constants are already defined in netcdf_constents.f90.
In this PR I add nf90_inq_format() and a test for classic and netCDF-4 builds.
Part of #263
> Added missing nf90_inq_format() function

- .travis.yml
- fortran/CMakeLists.txt
Disable hdf4 tests when compiling netcdf-c without hdf5 support.  See https://github.com/Unidata/netcdf-c/issues/1402 for more information.
> Tweak Travis-CI Settings

- configure.ac
This PR is to restore the previous functionality of `nf-config` as detailed in https://github.com/Unidata/netcdf-fortran/issues/270.
Currently, building netcdf-fortran with autotools results in `nf-config` that returns:
```
-L/Users/mathomp4/NetcdfFortranFix/before/lib 
-lnetcdff
```
where you only get out the `libnetcdff` link, but not everything you need to link to netcdf-fortran.
Before https://github.com/Unidata/netcdf-fortran/commit/82273f82f5f20ed5e2e64d847476dfc48b8f33ff, `nf-config --flibs` returned something like:
```
-L/Users/mathomp4/NetcdfFortranFix/after/lib 
-lnetcdff -lnetcdf -lm 
-L/Users/mathomp4/NetcdfFortranFix/after/lib 
-L/Users/mathomp4/NetcdfFortranFix/after/lib 
-lnetcdf -ljpeg -lmfhdf -ldf -ljpeg -lhdf5_hl -lhdf5 -lm -lz …
```
> Fix for nf-config using autotools

- .github/workflows/build.yml
- .gitignore
- docs/netcdf-f90-sec6-variables.md
- fortran/module_netcdf4_nc_interfaces.f90
- fortran/module_netcdf4_nf_interfaces.F90
- fortran/module_netcdf_nc_data.F90
- fortran/module_netcdf_nc_interfaces.f90
- fortran/module_netcdf_nf_data.F90
- fortran/netcdf4.inc
- fortran/netcdf4_externals.f90
- fortran/netcdf4_func.f90
- fortran/netcdf4_variables.f90
- fortran/netcdf4_visibility.f90
- fortran/netcdf_constants.f90
- fortran/nf_nc4.f90
- nf03_test4/CMakeLists.txt
- nf03_test4/Makefile.am
- nf03_test4/f90tst_vars5.f90
- nf03_test4/run_f90_par_test.sh
- nf_test4/CMakeLists.txt
- nf_test4/Makefile.am
- nf_test4/ftst_vars7.F
This won't work until the quantize PR in netcdf-c is merged (https://github.com/Unidata/netcdf-c/pull/2088).
Add the quantize feature to the Fortran APIs.
> Add quantize feature to F77 and F90 APIs, with tests and documentation

- configure.ac
Adding `-fallow-argument-mismatch` to `FFLAGS` as adding it to `FCFLAGS` was still resulting in failures when running `make check` on linux and OSX.
> Attempt to correct an issue being observed under linux and OSX with gfortran

- CMakeLists.txt
As with https://github.com/Unidata/netcdf-c/pull/2218, older versions of CMake than 3.12
are already broken with NetCDF and uncommon nowadays.
It may be better to explicitly require 3.12 or newer.
This also suppresses several nuisance warnings about unexpected behavior when using a modern CMake version.
> Rationalize CMake minimum version to 3.12

- .github/workflows/run_tests.yml
Github Actions has a mismatch between the cache and the test blocks.  This fixes that.
> Fix hdf5 version mismatch.

- nf_test/tst_f77_v2.F
This adds to one of the Fortran V2 API tests.
Part of #329.
This test seems to demonstrate that reading char arrays in the V2 API works just fine.
I will communicate with the NOAA programmers who felt they had a bug and see if I can figure out what they found, if anything.
Meanwhile, this is a good test.
> adding v2 api test

- CMakeLists.txt
- fortran/CMakeLists.txt
Solving: https://github.com/geospace-code/nc4fortran/issues/4
`-fPIC` was only set for APPLE or when using GNUCC compiler. In my case I ran into a linker error with Intel oneAPI on Ubuntu.
I don't know if setting `CMAKE_POSITION_INDEPENDENT_CODE ON` is to much, since I guess it will also affect the fortran tragets, so we could also only set the `POSITION_INDEPENDENT_CODE` property for the `netcdff_c` target.
This could also solve https://github.com/Unidata/netcdf-fortran/issues/35
> set 'CMAKE_POSITION_INDEPENDENT_CODE ON' for shared lib

- fortran/CMakeLists.txt
- fortran/Makefile.am
Look like this same fix has already appeared in fortran/CMakeLists.txt
by @brucenairn in 340b07a7b38529c9dbe0164f4339557be23c937e
> bug fix: when all parallel features are disabled in netcdf-c

- nf03_test4/CMakeLists.txt
The file was not generated/copied at the right place.
Fixes #340.
> CMake build: fix handling of run_f90_par_test.sh

- fortran/module_netcdf_nc_data.F90
- fortran/module_typesizes.F90
- fortran/netcdf.F90
See https://github.com/Unidata/netcdf-fortran/issues/427 for more information.
> Attempt to fix a pernicious issue where some systems complain about no implicit type.

- CMakeLists.txt
To follow cmake `find_pacakge()` search procedure rules, the install directory name should match the package name:
https://cmake.org/cmake/help/v3.20/command/find_package.html#search-procedure
With this change, now `find_package` should work even when specifying only `netCDF-Fortran_ROOT` (thus running in [Config Mode](https://cmake.org/cmake/help/v3.20/command/find_package.html#full-signature-and-config-mode)), which has the highest search precedence since CMake 3.12
Future improvements might include a variable to replace all instances of the string `netCDF-Fortran` so that variables or functions that ought to use the package name can source from one definition.
> Use install directory that matches package name

- CMakeLists.txt
- configure.ac
* Fixes #278 
Draft pull request, we need more than a simple message update.  I'll review to see if there's a way we can fencepost around the `szip` functionality we're checking for, and if we can introduce an alternative check that will allow linking against a libnetcdf 4.7.4+ linking against `libhdf5` built without szip support.
> Clarify 'netCDF-C 4.7.4 or greater required' message.

- CMakeLists.txt
* Fixes #278 
There may be an elegant solution, but for now we will just provide instructions alongside the error.  When cmake invokes `CHECK_LIBRARY_EXISTS()` against a static library (such as `libnetcdf.a`), the dependencies must be specified manually, since there is no way to infer these dependencies with static libraries; this can be handled programmatically in the `CMakeLists.txt` file, where we check for `nc-config` and, if present, use the output of `nc-config --libs`, but for now we will just present this information when encountering this error.  
The fix is to set `LDFLAGS` to the output from `nc-config --libs`.
> Clarify message when failing with 'requires v4.7.4' error. 

- fortran/CMakeLists.txt
If using the netcdf-C CMake build directory directly, then `NETCDF_C_LIBRARY` and `NETCDF_C_INCLUDE_DIR` won't be defined -- more consistent to link against `netCDF::netcdf` instead.
> CMake: Fix some issues when linking against netcdf-C
